#!/bin/bash

FEATURES_FILE="/var/tmp/dwm-panel.features"
CUSTOM_FILE="$HOME/.dwm-panel-custom"
touch $FEATURES_FILE
declare -A FEATURES

function rm_colors()
{
    sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
}

F_LOAD_FEATURE_FILE()
{
    for setting in $(cat $FEATURES_FILE)
    do
        feature=$(echo "$setting" | awk -F= '{print $1}')
        value=$(echo "$setting" | awk -F= '{print $2}')
        FEATURES["$feature"]=$value
    done
}

F_LOAD_FEATURE_FILE

BATTERY_TIME=0
LOAD_TIME=0
RAM_TIME=0
while true
do
    SHOW=""

    # CUSTOM MESSAGE
    CUSTOM=""
    test -e "$CUSTOM_FILE" && CUSTOM="$(cat "$CUSTOM_FILE")"

    # TIMED
    TIMED=""
    timed status | grep -q 'working'
    if [ $? -eq 0 ]
    then
        project=$(timed status | rm_colors | awk '/working/ {print $NF}')
        elapsed=$(timed status | rm_colors | awk '/elapsed/ {print $2}')
        TIMED="$project $elapsed | "
    fi

    # WAKELOCK
    WAKELOCK=""
    xset q | grep "DPMS is Disabled" > /dev/null && WAKELOCK="WL | " 2>/dev/null

    # LOAD
    if [ "${FEATURES["load"]}" = "1" ];then
        if [ "$LOAD_TIME" -eq 0 ] ; then
            LOAD_TIME=1
            LOAD="L: $( uptime | awk '{print $(NF-2)}' | sed 's/,//' ) | "
        fi
    fi

    # RAM
    if [ "${FEATURES["ram_usage"]}" = "1" ];then
        if [ "$RAM_TIME" -eq 0 ] ; then
            RAM_TIME=1
            RAM="RAM: $(free -m |awk '/Mem:/ { print $3"M" }') | "
        fi
    fi

    # VOLUME
    if [ "${FEATURES["volume"]}" = "1" ];then
        VOLUME="\xF0\x9F\x94\x8A $(amixer get Master | grep "%" | sed  "s/.*\[\([0-9]\{0,3\}\)%\].*\[on\].*/\1%/g" | sed "s/.*\[off\].*/mute/g" | tail -n 1) | "
        echo "$VOLUME" | grep -q 'mute' && VOLUME="\xF0\x9F\x94\x88 | "
    fi

    # BATTERY
    if [ "${FEATURES["battery"]}" = "1" ];then
        # Every 1 minute
        if [ "$BATTERY_TIME" -eq 0 ] ; then
            BATTERY_TIME=2
            REMAINING=$(acpi -V | grep 'Battery 0: Discharging' | grep remaining | head -n 1 | awk '{print $(NF-1)}' | awk -F':' '{print $1 "h" $2 "m" }' | sed "s/00h//")
            test x"$REMAINING" = x || REMAINING=" $REMAINING"
            BATTERY="\xF0\x9F\x94\x8B`acpi -V | head -n 1 | awk -F',' '{print $2}'`$REMAINING"

            if acpi -V | grep -q 'Battery 1'
            then
                REMAINING=$(acpi -V | grep 'Battery 1: Discharging' | grep remaining | head -n 1 | awk '{print $(NF-1)}' | awk -F':' '{print $1 "h" $2 "m" }' | sed "s/00h//")
                test x"$REMAINING" = x || REMAINING="$REMAINING "
                BATTERY="$BATTERY`acpi -V | grep 'Battery 1' | head -n 1 | awk -F',' '{print $2}'` $REMAINING"
            fi
            BATTERY="$BATTERY| "
        fi
    fi

    # TIME
    TIME="$(date +%H:%M:%S) | $(date +%d.%m.%Y)"
    if [ "${FEATURES["keyboard-layout"]}" = "1" ];then
        layout=`setxkbmap -query | grep ^layout | awk '{print $2}' | sed 's/ //g'`
        variant="`setxkbmap -query | grep ^variant | awk '{print $2}'`"
        test "x$variant" = "x" && KEYBOARD="${layout} | " || KEYBOARD="${layout}/${variant} | "
    fi

    # KEYBOARD LAYOUT
    TIME="$(date +%H:%M) | $(date +%d.%m.%Y)"

    SHOW="${CUSTOM}${TIMED}${KEYBOARD}${WAKELOCK}${RAM}${LOAD}${VOLUME}${BATTERY}${TIME}"
    xsetroot -name "$(echo -e "$SHOW")"

    ((BATTERY_TIME=$BATTERY_TIME-1))
    ((LOAD_TIME=$LOAD_TIME-1))
    ((RAM_TIME=$RAM_TIME-1))
    sleep 30 &
    echo $! > $HOME/.dwm-panel-sleep.pid
    wait
done
