#!/bin/bash
# Black background
xsetroot -solid black
# Fix for Java apps
wmname LG3D
# Launch DBus if needed
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi
# Start polkit agent
/usr/libexec/lxpolkit &

# Start dwm-panel
dwm-panel start

# Start $HOME/.dwm-start if exists
test -e $HOME/.dwm-start && $HOME/.dwm-start &

while true; do
    dwm || { /usr/bin/dwm-panel stop; exit; }
done
