#!/bin/bash
service dwm-panel start

# Black background
xsetroot -solid black
# Fix for Java apps
wmname LG3D
# Launch DBus if needed
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi
# Start polkit agent
/usr/libexec/lxpolkit &


while true; do
	dwm || exit
done
